=== CERNDocumentServer/cds-videos/cds/modules/records/schemas/categories/category-v1.0.0.json
{
  "title": "CDS Deposit Category Schema.",
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "name": {
      "description": "TODO",
      "type": "string"
    },
    "types": {
      "description": "TODO",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "access": {
      "type": "object",
      "properties": {
        "public": {
          "type": "boolean"
        },
        "restricted": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "_record_type": {
      "description": "TODO",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== CERNDocumentServer/cds-videos/cds/modules/fixtures/data/categories.json
[
  {
    "name": "CERN",
    "types": ["FOOTAGE", "VIDEO"],
    "access": {
      "public": true,
      "restricted": [
        "audiovisual-support@cern.ch",
        "it-dep-uds-avc@cern.ch",
        "editorial-group@cern.ch",
        "hr-video-group@cern.ch",
        "visualmedia-office@cern.ch",
        "vmo-restictedrights@cern.ch"
      ]
    },
    "_record_type": ["PROJECT"]
  },
  {
    "name": "ATLAS",
    "types": ["FOOTAGE", "VIDEO"],
    "access": {
      "public": true,
      "restricted": ["atlas-readaccess-active-members@cern.ch"]
    },
    "_record_type":  ["PROJECT"]
  },
  {
    "name": "CMS",
    "types": ["VIDEO"],
    "access": {
      "public": true,
      "restricted": []
    },
    "_record_type":  ["PROJECT"]
  },
  {
    "name": "OPEN",
    "types": ["VIDEO"],
    "access": {
      "public": true,
      "restricted": []
    },
    "_record_type":  ["PROJECT"]
  },
  {
    "name": "SCADA",
    "types": ["VIDEO"],
    "access": {
      "public": true,
      "restricted": []
    },
    "_record_type":  ["PROJECT"]
  }
]
